name: Generate Lilypond music sheets
on:
  push:
    branches:
      - gh-pages
jobs:
  build_sheets:
    runs-on: ubuntu-latest
    env:
        LILYPOND_FILES: "*.ly"
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v1
      - name: Get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(find ${{github.workspace}} -name "${{ env.LILYPOND_FILES }}" -printf "%P\n" | xargs)"
      - name: LILYPOND files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: Generate PDF music sheets
        uses: alexandre-touret/lilypond-github-action@master
        with:
            args: -V -f --pdf ${{ steps.getfile.outputs.files }}
      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
        with: 
          commit_user_name: ${{secrets.GIT_USERNAME}}
          commit_user_email: ${{secrets.GIT_EMAIL}}
          commit_author: ${{secrets.GIT_USERNAME}} <${{secrets.GIT_EMAIL}}>
          commit_message: "Generate PDF" 
          branch: gh-pages
