name: Generate Lilypond music sheets
on:
  push:
    branches:
      - gh-pages
jobs:
  build_sheets:
    runs-on: ubuntu-latest
    env:
        LILYPOND_FILES: ".ly"
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v1
      - name: Get changed files
        id: getfile
        run: |
          find ${{github.workspace}} -name ${{ env.LILYPOND_FILES }}
      - name: LILYPOND files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: Generate PDF music sheets
        uses: alexandre-touret/lilypond-github-action@master
        with:
            args: -V -f --pdf 
      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
        with: 
          commit_user_name: "${{github.actor}}"
          commit_user_email: "me@email.org"
          commit_author: "My User <me@email.org>"
          commit_message: "Generate PDF" 
          branch: ${{ github.head_ref }}